// Each guide: slug, group, title, desc, sections[{ h, p?, items?[[title, text]] }], notice?, links?[[label, url]]
export const guides = [
  {
    slug: "regional-baby-names",
    group: "Baby names",
    title: "Regional baby names",
    desc: "Names rooted in the nations and regions of the British Isles.",
    sections: [
      { h: "Welsh names", p: "Welsh names carry strong sounds and clear meanings. Many suit any accent.", items: [["Rhys", "Ardor, enthusiasm"], ["Cerys", "Love"], ["Seren", "Star"], ["Owen", "Young warrior"], ["Megan", "Pearl"]] },
      { h: "Scottish and Gaelic names", p: "Gaelic spellings look different from how they sound. Check the pronunciation before you decide.", items: [["Isla", "From the river and island name"], ["Fraser", "A clan surname turned first name"], ["Eilidh", "A Gaelic form of Helen, said AY-lee"], ["Callum", "Dove"]] },
      { h: "Irish names", p: "Irish names use traditional spellings. Expect to spell them out for others.", items: [["Aoife", "Beauty, said EE-fa"], ["Niamh", "Bright, said NEEV"], ["Cian", "Ancient"], ["Saoirse", "Freedom, said SEER-sha"]] },
      { h: "English names", p: "Old English names are enjoying a revival, especially short and nature-based ones.", items: [["Wren", "A small songbird"], ["Alfie", "Elf counsel"], ["Edith", "Prosperous in war"], ["Arthur", "Bear, noble"]] },
    ],
  },
  {
    slug: "baby-name-origins",
    group: "Baby names",
    title: "Names by origin",
    desc: "Where names come from and what they meant first.",
    sections: [
      { h: "Latin and Greek", p: "Many classic names trace back to Rome and Greece.", items: [["Clara", "Latin, bright and clear"], ["Julian", "Latin, from the Julius family"], ["Sophia", "Greek, wisdom"], ["Theodore", "Greek, gift of God"]] },
      { h: "Hebrew", p: "Hebrew names appear across many cultures and faiths.", items: [["Noah", "Rest, comfort"], ["Hannah", "Grace"], ["Daniel", "God is my judge"], ["Eve", "Life"]] },
      { h: "Arabic and Sanskrit", p: "These names are growing in use across the UK.", items: [["Amira", "Arabic, princess"], ["Zain", "Arabic, grace"], ["Anaya", "Sanskrit, caring"], ["Arjun", "Sanskrit, bright"]] },
      { h: "Old English and Norse", p: "Short, strong sounds define this group.", items: [["Freya", "Norse, noble lady"], ["Oscar", "Old Irish and Old English roots, friend of deer"], ["Harold", "Army ruler"], ["Erin", "Old Irish, Ireland"]] },
    ],
    notice: "Meanings vary between sources. Treat any single meaning as a starting point.",
  },
  {
    slug: "celebrity-baby-names",
    group: "Baby names",
    title: "Celebrity baby names",
    desc: "How famous families shape what the rest of us choose.",
    sections: [
      { h: "How fame moves a name", p: "A well known name draws attention. Some names rise within a year of a public birth announcement. Others fade once the novelty ends." },
      { h: "Ask before you copy", items: [["Will it last?", "Picture the name on a school register and on a job application."], ["Say it aloud", "Try it with your surname and with a shout across a park."], ["Check initials", "Make sure the initials spell nothing awkward."], ["Think about siblings", "Names that pair well now still work in ten years."]] },
      { h: "Make it your own", p: "Use a famous name as inspiration only. A family surname, a place or a grandparent's name gives a similar feel with more meaning." },
    ],
  },
  {
    slug: "baby-name-trends",
    group: "Baby names",
    title: "Baby name trends",
    desc: "The styles families choose, and where to check current rankings.",
    sections: [
      { h: "Styles in favour", items: [["Short names", "Two syllables or fewer, easy to say and spell."], ["Nature names", "Plants, birds, seasons and landscapes."], ["Vintage revival", "Names from a grandparent's generation."], ["Gender-neutral names", "Names that suit any child."]] },
      { h: "Check current rankings", p: "The Office for National Statistics publishes the most popular names in England and Wales each year. Rankings change, so look at the latest release rather than an old list." },
    ],
    links: [["Office for National Statistics", "https://www.ons.gov.uk"]],
  },
  {
    slug: "weaning",
    group: "Baby",
    title: "Weaning",
    desc: "When to start solid food and how to begin safely.",
    sections: [
      { h: "When to start", p: "Most babies are ready around six months. Milk stays the main drink until 12 months.", items: [["Sits up", "Sits with little support and holds their head steady."], ["Reaches and grabs", "Brings food to their mouth."], ["Swallows food", "Pushes less food back out with their tongue."]] },
      { h: "Good first foods", p: "Offer soft, cooked vegetables, mashed fruit, porridge and soft finger foods. Let your baby set the pace." },
      { h: "Foods to avoid", items: [["Honey", "Do not give before 12 months."], ["Added salt and sugar", "Baby kidneys are still developing."], ["Whole nuts", "A choking risk. Serve nut butters thinly spread."], ["Whole grapes and cherry tomatoes", "Cut them lengthways into quarters."]] },
      { h: "Allergens", p: "Introduce foods such as egg, peanut butter and wheat one at a time, in small amounts, from around six months. Ask your health visitor if your baby has eczema or a family history of allergy." },
    ],
    notice: "Gagging is normal and noisy. Choking is silent. Take an infant first aid course before weaning starts.",
  },
  {
    slug: "safer-sleep",
    group: "Baby",
    title: "Safer sleep",
    desc: "Simple steps that lower the risk of sudden infant death.",
    sections: [
      { h: "Every sleep, day or night", items: [["On the back", "Place your baby on their back, on a firm, flat surface."], ["Feet to the foot", "Position feet at the foot of the cot."], ["Clear cot", "Leave out pillows, duvets, bumpers and soft toys."], ["Room sharing", "Keep the cot in your room for the first six months."], ["Not too warm", "A room temperature of 16 to 20 degrees works well."]] },
      { h: "Sofas and armchairs", p: "Never sleep with your baby on a sofa or armchair. If you feel very tired during a feed, move to a bed and remove pillows and covers." },
      { h: "Smoke and alcohol", p: "Keep your home and car smoke free. Do not share a bed after drinking alcohol or taking drugs that make you drowsy." },
    ],
    links: [["The Lullaby Trust", "https://www.lullabytrust.org.uk"]],
  },
  {
    slug: "postnatal-depression",
    group: "Baby",
    title: "Postnatal depression and bonding",
    desc: "Signs to look for, and how to get help fast.",
    sections: [
      { h: "Baby blues or something more", p: "Tearfulness in the first two weeks is common and usually passes. Low mood that lasts longer, or gets worse, needs support. Around one in ten women has postnatal depression, and partners are affected too." },
      { h: "Signs to look for", items: [["Low mood", "Feeling sad, empty or numb most days."], ["Anxiety", "Constant worry or panic."], ["Bonding trouble", "Feeling distant from your baby."], ["Sleep and appetite", "Problems beyond what a newborn causes."], ["Intrusive thoughts", "Frightening thoughts you cannot switch off."]] },
      { h: "Getting help", p: "Tell your GP, health visitor or midwife. Treatment works, and it includes talking therapy, support groups and medicine. In England you also refer yourself to NHS talking therapies." },
    ],
    notice: "If you have thoughts of harming yourself or your baby, or you see or hear things others do not, call 999 or go to A&E now. Samaritans answer any time on 116 123.",
    links: [["NHS: postnatal depression", "https://www.nhs.uk/mental-health/conditions/post-natal-depression/"]],
  },
  {
    slug: "toddler-immunisations",
    group: "Toddler",
    title: "Your toddler's immunisations",
    desc: "What to expect at the one year appointment and after.",
    sections: [
      { h: "Why they matter", p: "Vaccines protect your child from serious illness and protect babies too young to be fully vaccinated." },
      { h: "At 12 months", p: "Your GP surgery invites you. This visit includes boosters against Hib and meningitis C, pneumococcal disease and meningitis B, plus the first MMR dose." },
      { h: "Later doses", p: "Further doses follow at older ages. The schedule changes from time to time, so check the current NHS timetable and your child's Red Book." },
      { h: "After the jab", items: [["Sore arm or leg", "Common for a day or two."], ["Mild fever", "Give liquid paracetamol or ibuprofen as the label directs."], ["Fussy and sleepy", "Offer extra cuddles and fluids."]] },
    ],
    notice: "Call 111 if your child has a very high temperature, will not feed or drink, or seems unusually drowsy. Call 999 for breathing trouble or a seizure.",
    links: [["NHS vaccination schedule", "https://www.nhs.uk/vaccinations/nhs-vaccinations-and-when-to-have-them/"]],
  },
  {
    slug: "family-illness-a-z",
    group: "Family",
    title: "A to Z of family illness",
    desc: "Common childhood illnesses and what to do at home.",
    sections: [
      { h: "Common illnesses", items: [
        ["Chickenpox", "Itchy spots that crust over. Keep your child cool, trim nails and use paracetamol. Avoid ibuprofen. Keep away from pregnant women."],
        ["Colds", "Runny nose and cough for up to two weeks. Offer fluids and rest."],
        ["Conjunctivitis", "Red, sticky eyes. Clean with cooled boiled water and wash hands often."],
        ["Croup", "Barking cough, worse at night. Stay calm. Call 111 if breathing looks hard."],
        ["Ear infection", "Ear pain and fever. Pain relief helps. See your GP if it lasts over three days."],
        ["Gastroenteritis", "Sickness and diarrhoea. Give small, frequent sips. Watch for dehydration."],
        ["Hand, foot and mouth", "Mouth ulcers and spots on hands and feet. It clears in about a week."],
        ["Slapped cheek", "Bright red cheeks and a lacy rash. Tell your midwife if you are pregnant and exposed."],
        ["Tonsillitis", "Sore throat and fever. Fluids and pain relief. See your GP if it lasts."],
      ] },
    ],
    notice: "Call 999 if your child struggles to breathe, turns blue or grey, will not wake, or has a seizure. Press a glass on a rash. If it does not fade, get help at once. Call 111 for anything else that worries you.",
    links: [["NHS: children's health", "https://www.nhs.uk/conditions/baby/"]],
  },
];

export const getGuide = (slug) => guides.find((g) => g.slug === slug);
